# Generated by Django 2.0.5 on 2018-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readdetail',
            old_name='readed_num',
            new_name='read_num',
        ),
        migrations.RemoveField(
            model_name='readnum',
            name='readed_num',
        ),
        migrations.AddField(
            model_name='readnum',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
